package edu.uga.cs.countryquiz;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import java.util.ArrayList;
import java.util.List;

/**
 * This class is facilitates storing and restoring countries data and past quizzes stored.
 */
public class CountriesData {
    public static final String DEBUG_TAG = "CountriesData";

    // this is a reference to our database; it is used later to run SQL commands
    private SQLiteDatabase   db;
    private final SQLiteOpenHelper dbHelper;
    private static final String[] allColumns = {
            QuizDBHelper.COUNTRIES_COLUMN_ID,
            QuizDBHelper.COUNTRIES_COLUMN_NAME,
            QuizDBHelper.COUNTRIES_COLUMN_CAPITAL,
            QuizDBHelper.COUNTRIES_COLUMN_CONTINENT,
    };

    public CountriesData( Context context ) {
        dbHelper = QuizDBHelper.getInstance( context );
    }

    // Open the database
    public void open() {
        db = dbHelper.getWritableDatabase();
        Log.d( DEBUG_TAG, "CountriesData: db open" );
    }

    // Close the database
    public void close() {
        if( dbHelper != null ) {
            dbHelper.close();
            Log.d(DEBUG_TAG, "CountriesData: db closed");
        }
    }

    public boolean isDBOpen()
    {
        return db.isOpen();
    }

    // Retrieve all countries and return them as a List.
    // This is how we restore persistent objects stored as rows in the job leads table in the database.
    // For each retrieved row, we create a new JobLead (Java POJO object) instance and add it to the list.
    public List<Country> retrieveAllCountries() {
        ArrayList<Country> Countries = new ArrayList<>();
        Cursor cursor = null;

        try {
            // Execute the select query and get the Cursor to iterate over the retrieved rows
            cursor = db.query( QuizDBHelper.TABLE_COUNTRIES, allColumns,
                    null, null, null, null, null );

            // collect all job leads into a List
            if( cursor != null && cursor.getCount() > 0 ) {

                while( cursor.moveToNext() ) {

                        long id = cursor.getLong(
                                cursor.getColumnIndexOrThrow(QuizDBHelper.COUNTRIES_COLUMN_ID));

                        String name = cursor.getString(
                                cursor.getColumnIndexOrThrow(QuizDBHelper.COUNTRIES_COLUMN_NAME));

                        String capital = cursor.getString(
                                cursor.getColumnIndexOrThrow(QuizDBHelper.COUNTRIES_COLUMN_CAPITAL));

                        String continent = cursor.getString(
                                cursor.getColumnIndexOrThrow(QuizDBHelper.COUNTRIES_COLUMN_CONTINENT));

                        // create a new country object and set its state to the retrieved values
                        Country country = new Country();
                        country.setId(id);
                        country.setName(name);
                        country.setCapital(capital);
                        country.setContinent(continent);

                        Countries.add(country);

                        Log.d(DEBUG_TAG, "Retrieved Country: " + country);
                }
            }
            if( cursor != null )
                Log.d( DEBUG_TAG, "Number of records from DB: " + cursor.getCount() );
            else
                Log.d( DEBUG_TAG, "Number of records from DB: 0" );
        }
        catch( Exception e ){
            Log.d( DEBUG_TAG, "Exception caught: " + e );
        }
        finally{
            // we should close the cursor
            if (cursor != null) {
                cursor.close();
            }
        }
        // return a list of retrieved countries
        return Countries;
    }

    // Store a new country in the database.
    public void storeCountry( Country country ) {

        // Prepare the values for all of the necessary columns in the table
        // and set their values to the variables of the JobLead argument.
        // This is how we are providing persistence to a JobLead (Java object) instance
        // by storing it as a new row in the database table representing job leads.
        ContentValues values = new ContentValues();
        values.put( QuizDBHelper.COUNTRIES_COLUMN_NAME, country.getName());
        values.put( QuizDBHelper.COUNTRIES_COLUMN_CAPITAL, country.getCapital() );
        values.put( QuizDBHelper.COUNTRIES_COLUMN_CONTINENT, country.getContinent() );

        // Insert the new row into the countries table;
        // The id (primary key) is automatically generated by the database system
        // and returned as from the insert method call.
        long id = db.insert( QuizDBHelper.TABLE_COUNTRIES, null, values );

        // store the id (the primary key) in the country instance, as it is now persistent
        country.setId( id );

        Log.d( DEBUG_TAG, "Stored new country with id: " + String.valueOf( country.getId() ) );
    }

    // Store a new score in the database
    public void storeQuiz(int score, String date) {

        ContentValues values = new ContentValues();
        values.put(QuizDBHelper.QUIZZES_COLUMN_SCORE, score);
        values.put(QuizDBHelper.QUIZZES_COLUMN_DATE, date);

        db.insert(QuizDBHelper.TABLE_QUIZZES, null, values);

        Log.d(DEBUG_TAG, "Stored quiz score: " + score);
    }

}
